http://localhost:8080/listTasks

###



POST http://localhost:8080/createTask
Content-Type: application/json

{
  "taskName": "Sample Task Name2",
  "taskDescription": "Sample Description2",
  "complete": "false"
}

###

POST http://localhost:8080/updateTask
Content-Type: application/json

{
  "taskId": "a081503e-cb21-4b00-9a3c-6519893963cb",
  "taskName": "Updated to the db",
  "taskDescription": "Updated to the db",
  "complete": false
}

###

POST http://localhost:8080/completeTask?taskId=a081503e-cb21-4b00-9a3c-6519893963cb
Content-Type: application/json
###
